### PR TITLE
Getcwd rust

### PR DESCRIPTION
**Pull request by youngfalcon**
Implemented the getcwd syscall

### CODE REVIEW

**Review by rennergade — APPROVED** [review]
This looks good! You need to resolve the conflict with my recent PR tho, sorry!

**Comment by youngfalcon** [comment]
> This looks good! You need to resolve the conflict with my recent PR tho, sorry!

Done.

**Review by kapkic — APPROVED** [review]
Looks good!

**Review by jesings — APPROVED** [review]
Looks nice!

**Pull request merged**
